### ISSUE TITLE
rsync fails at provision: ssh_info[:private_key_path] evaluates to array containing path instead of path

### ISSUE THREAD

**Issue by cdmsn** [NeilW/vagrant-brightbox#2]
I discovered issue mitchellh/vagrant-aws#171 now with Vagrant 1.4.3.
I used https://github.com/tmatilai/vagrant-aws/commit/4a043a96076c332220ec4ec19470c4af5597dd51 quick and dirty to fix it for now.

**Comment by NeilW** [comment]
0.3.0 should fix this problem by using the upstream Sync Folders middleware.
